<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Document</title>';
echo '<link rel="stylesheet" href="index.css">';
echo '<!-- If You don't wish to use index.css you can alternatively use the link';
echo 'https://cdnjs.cloudflare.com/ajax/libs/flickity/1.0.0/flickity.css';
echo '';
echo 'then add this later';
echo '';
echo '/* external css: flickity.css */';
echo '';
echo '* {';
echo '-webkit-box-sizing: border-box;';
echo 'box-sizing: border-box;';
echo '}';
echo '';
echo 'body { font-family: sans-serif; }';
echo '';
echo '.gallery {';
echo 'background: #EEE;';
echo '}';
echo '';
echo '.gallery-cell {';
echo 'width: 66%;';
echo 'height: 200px;';
echo 'margin-right: 10px;';
echo 'background: #8C8;';
echo 'counter-increment: gallery-cell;';
echo '}';
echo '';
echo '/* cell number */';
echo '.gallery-cell:before {';
echo 'display: block;';
echo 'text-align: center;';
echo 'content: counter(gallery-cell);';
echo 'line-height: 200px;';
echo 'font-size: 80px;';
echo 'color: white;';
echo '}';
echo '-->';
echo '<script src="index.js"></script>';
echo '<!-- index.js alternative link:';
echo 'https://cdnjs.cloudflare.com/ajax/libs/flickity/1.0.0/flickity.pkgd.js -->';
echo '<script>';
echo 'var myScope = document;';
echo 'var iframes = myScope.getElementsByTagName("iframe");';
echo 'if (iframes != null) {';
echo 'for (var i = 0; i < iframes.length; i++) {';
echo 'iframes[i].src = iframes[i].src; //causes a reload so it stops playing, music, video, etc.';
echo '}';
echo '}';
echo '</script>';
echo '</head>';
echo '<body>';
echo '';
echo '';
echo '<!-- Flickity HTML init -->';
echo '<div class="gallery js-flickity"';
echo 'data-flickity-options='{ "freeScroll": false, "wrapAround": true }'>';
echo '<div id="divScope">';
echo '<iframe width="853" height="480" src="https://www.youtube.com/embed/Fnw4hr7p43Y"  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
echo '</div>';
echo '<div >';
echo '<iframe width="853" height="480" src="https://www.youtube.com/embed/Fnw4hr7p43Y"  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
echo '</div>';
echo '<div >';
echo '<iframe width="853" height="480" src="https://www.youtube.com/embed/Fnw4hr7p43Y"  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
echo '</div>';
echo '<div >';
echo '<iframe width="853" height="480" src="https://www.youtube.com/embed/Fnw4hr7p43Y"  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '</body>';
echo '</html>';
?>